### PR TITLE
Detect internal Kotlin types and mark them inaccessible

### LINKED ISSUE #856: The hello-android sample is broken on develop branch
Just checked out the hello-android sample on the develop branch and got this message on syncing with android studio:
```
Failed to compile accessors.

    projectSchema: ProjectSchema(extensions=[ProjectSchemaEntry(target=org.gradle.api.Project, name=ext, type=org.gradle.api.plugins.ExtraPropertiesExtension), ProjectSchemaEntry(target=org.gradle.api.Project, name=defaultArtifacts, type=org.gradle.api.internal.plugins.DefaultArtifactPublicationSet), ProjectSchemaEntry(target=org.gradle.api.internal.plugins.DefaultArtifactPublicationSet, name=ext, type=org.gradle.api.plugins.ExtraPropertiesExtension), ProjectSchemaEntry(target=org.gradle.api.Project, name=reporting, type=org.gradle.api.reporting.ReportingExtension), ProjectSchemaEntry(target=org.gradle.api.reporting.ReportingExtension, name=ext, type=org.gradle.api.plugins.ExtraPropertiesExtension), ProjectSchemaEntry(target=org.gradle.api.Project, name=buildOutputs, type=org.gradle.api.NamedDomainObjectContainer<com.android.build.gradle.api.BaseVariantOutput>), ProjectSchemaEntry(target=org.gradle.api.NamedDomainObjectContainer<com.android.build.gradle.api.BaseVariantOutput>, name=ext, type=org.gradle.api.plugins.ExtraPropertiesExtension), ProjectSchemaEntry(target=org.gradle.api.Project, name=android, type=com.android.build.gradle.AppExtension), ProjectSchemaEntry(target=com.android.build.gradle.AppExtension, name=ext, type=org.gradle.api.plugins.ExtraPropertiesExtension), ProjectSchemaEntry(target=com.android.build.gradle.AppExtension, name=kotlinOptions, type=org.jetbrains.kotlin.gradle.dsl.KotlinJvmOptionsImpl), ProjectSchemaEntry(target=org.gradle.api.Project, name=kotlin, type=org.jetbrains.kotlin.gradle.dsl.KotlinProjectExtension), ProjectSchemaEntry(target=org.jetbrains.kotlin.gradle.dsl.KotlinProjectExtension, name=ext, type=org.gradle.api.plugins.ExtraPropertiesExtension), ProjectSchemaEntry(target=org.jetbrains.kotlin.gradle.dsl.KotlinProjectExtension, name=experimental, type=org.jetbrains.kotlin.gradle.dsl.ExperimentalExtension), ProjectSchemaEntry(target=org.jetbrains.kotlin.gradle.dsl.ExperimentalExtension, name=ext, type=org.gradle.api.plugins.ExtraPropertiesExtension), ProjectSchemaEntry(target=org.gradle.api.Project, name=kapt, type=org.jetbrains.kotlin.gradle.plugin.KaptExtension), ProjectSchemaEntry(target=org.jetbrains.kotlin.gradle.plugin.KaptExtension, name=ext, type=org.gradle.api.plugins.ExtraPropertiesExtension)], conventions=[ProjectSchemaEntry(target=org.gradle.api.Project, name=base, type=org.gradle.api.plugins.BasePluginConvention), ProjectSchemaEntry(target=org.gradle.api.Project, name=java, type=org.gradle.api.plugins.JavaPluginConvention)], configurations=[androidJacocoAgent, androidJacocoAnt, androidTestAnnotationProcessor, androidTestApi, androidTestApk, androidTestCompile, androidTestCompileOnly, androidTestDebugAnnotationProcessor, androidTestDebugApi, androidTestDebugApk, androidTestDebugCompile, androidTestDebugCompileOnly, androidTestDebugImplementation, androidTestDebugProvided, androidTestDebugRuntimeOnly, androidTestDebugWearApp, androidTestImplementation, androidTestProvided, androidTestRuntimeOnly, androidTestUtil, androidTestWearApp, annotationProcessor, api, apk, archives, compile, compileOnly, debugAnnotationProcessor, debugApi, debugApk, debugCompile, debugCompileOnly, debugImplementation, debugProvided, debugRuntimeOnly, debugWearApp, default, implementation, kapt, kaptAndroidTest, kaptAndroidTestDebug, kaptDebug, kaptRelease, kaptTest, kaptTestDebug, kaptTestRelease, lintChecks, provided, releaseAnnotationProcessor, releaseApi, releaseApk, releaseCompile, releaseCompileOnly, releaseImplementation, releaseProvided, releaseRuntimeOnly, releaseWearApp, runtimeOnly, testAnnotationProcessor, testApi, testApk, testCompile, testCompileOnly, testDebugAnnotationProcessor, testDebugApi, testDebugApk, testDebugCompile, testDebugCompileOnly, testDebugImplementation, testDebugProvided, testDebugRuntimeOnly, testDebugWearApp, testImplementation, testProvided, testReleaseAnnotationProcessor, testReleaseApi, testReleaseApk, testReleaseCompile, testReleaseCompileOnly, testReleaseImplementation, testReleaseProvided, testReleaseRuntimeOnly, testReleaseWearApp, testRuntimeOnly, testWearApp, wearApp])

    classPath: [/Users/stefan/.gradle/caches/4.8-20180430152641+0000/generated-gradle-jars/gradle-api-4.8-20180430152641+0000.jar, /Users/stefan/.gradle/wrapper/dists/gradle-kotlin-dsl-4.8-20180430152641+0000-all/2qzygyxc93rp1i28r3np9kn1m/gradle-4.8-20180430152641+0000/lib/groovy-all-2.4.12.jar, /Users/stefan/.gradle/wrapper/dists/gradle-kotlin-dsl-4.8-20180430152641+0000-all/2qzygyxc93rp1i28r3np9kn1m/gradle-4.8-20180430152641+0000/lib/gradle-installation-beacon-4.8.jar, /Users/stefan/.gradle/caches/4.8-20180430152641+0000/generated-gradle-jars/gradle-kotlin-dsl-extensions-0.17.1-SNAPSHOT-4.8-20180430152641+0000.jar, /Users/stefan/.gradle/wrapper/dists/gradle-kotlin-dsl-4.8-20180430152641+0000-all/2qzygyxc93rp1i28r3np9kn1m/gradle-4.8-20180430152641+0000/lib/gradle-kotlin-dsl-0.17.1-SNAPSHOT.jar, /Users/stefan/.gradle/wrapper/dists/gradle-kotlin-dsl-4.8-20180430152641+0000-all/2qzygyxc93rp1i28r3np9kn1m/gradle-4.8-20180430152641+0000/lib/gradle-kotlin-dsl-provider-spi-0.17.1-SNAPSHOT.jar, /Users/stefan/.gradle/wrapper/dists/gradle-kotlin-dsl-4.8-20180430152641+0000-all/2qzygyxc93rp1i28r3np9kn1m/gradle-4.8-20180430152641+0000/lib/gradle-kotlin-dsl-tooling-models-0.17.1-SNAPSHOT.jar, /Users/stefan/.gradle/wrapper/dists/gradle-kotlin-dsl-4.8-20180430152641+0000-all/2qzygyxc93rp1i28r3np9kn1m/gradle-4.8-20180430152641+0000/lib/kotlin-reflect-1.2.41.jar, /Users/stefan/.gradle/wrapper/dists/gradle-kotlin-dsl-4.8-20180430152641+0000-all/2qzygyxc93rp1i28r3np9kn1m/gradle-4.8-20180430152641+0000/lib/kotlin-stdlib-1.2.41.jar, /Users/stefan/.gradle/wrapper/dists/gradle-kotlin-dsl-4.8-20180430152641+0000-all/2qzygyxc93rp1i28r3np9kn1m/gradle-4.8-20180430152641+0000/lib/kotlin-stdlib-jdk7-1.2.41.jar, /Users/stefan/.gradle/wrapper/dists/gradle-kotlin-dsl-4.8-20180430152641+0000-all/2qzygyxc93rp1i28r3np9kn1m/gradle-4.8-20180430152641+0000/lib/kotlin-stdlib-jdk8-1.2.41.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/com.android.tools.build/gradle/3.0.1/cfa107d4db0c11c11f445a11e768adf61c72ce06/gradle-3.0.1.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/com.android.tools.build/gradle-core/3.0.1/c2945119335b491ca56e4042f7c8c55dccf5c9c2/gradle-core-3.0.1.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-gradle-plugin/1.2.41/18587320bcaffacd1fca5bda7fe0e3e63acc4d30/kotlin-gradle-plugin-1.2.41.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/com.android.tools.build/builder/3.0.1/1f896967507729bb35ac727c03d3b9306fe87b7d/builder-3.0.1.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/com.android.tools.lint/lint/26.0.1/541bfb082a95a3b55d0158d69b067f1d7c623122/lint-26.0.1.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/com.android.tools.lint/lint-checks/26.0.1/a5df32c64598e190808accaa03820fb9db9f8201/lint-checks-26.0.1.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/com.android.tools.lint/lint-api/26.0.1/2d4dd9f4676fbb152e4baf6f6f4cbbb868521832/lint-api-26.0.1.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/com.android.tools.external.org-jetbrains/uast/26.0.1/663906c592ce867fa2e9bcbffbe2130397078132/uast-26.0.1.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/com.android.tools.build/gradle-api/3.0.1/92640ae3c543aa3faee7b954ce641d03949d4401/gradle-api-3.0.1.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/com.android.databinding/compilerCommon/3.0.1/7f51b3e1636063e491131a0b0436512131cb1bdc/compilerCommon-3.0.1.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-gradle-plugin-api/1.2.41/b02a60e83beaa777c13562fd3e9612ea1963091d/kotlin-gradle-plugin-api-1.2.41.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-annotation-processing-gradle/1.2.41/870d8f3b110200303a07d4bbfc7bf9066669203b/kotlin-annotation-processing-gradle-1.2.41.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-android-extensions/1.2.41/10100eedfe2e26b9cf18b850d997b42d02af7500/kotlin-android-extensions-1.2.41.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-compiler-embeddable/1.2.41/e439cfdc216b070ebd454da892447f5dca96a934/kotlin-compiler-embeddable-1.2.41.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-reflect/1.2.41/e4d6728a4fa55dbfb510aeea25c072c7c51d94/kotlin-reflect-1.2.41.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/com.android.tools.build/manifest-merger/26.0.1/700cbb1ed4066f48d4970f5669c44a51bd03142/manifest-merger-26.0.1.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/com.android.tools/sdk-common/26.0.1/9ddd2fa552e7b49548c421c0be4e65dc9a245f69/sdk-common-26.0.1.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/com.android.tools/sdklib/26.0.1/bdb4723f8e3791f1d3911b1f191acf25840f352a/sdklib-26.0.1.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/com.android.tools/repository/26.0.1/bc0dfe02af8d075f6b7ad63a202ed4c63a6a647d/repository-26.0.1.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.2.41/7e34f009642702250bccd9e5255866f408962a05/kotlin-stdlib-1.2.41.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/com.android.tools.build/transform-api/2.0.0-deprecated-use-gradle-api/85bee1acea9e27152b920746c68133b30b11431/transform-api-2.0.0-deprecated-use-gradle-api.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm-analysis/5.1/6d1bf8989fc7901f868bee3863c44f21aa63d110/asm-analysis-5.1.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm-commons/5.1/25d8a575034dd9cfcb375a39b5334f0ba9c8474e/asm-commons-5.1.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm-util/5.1/b60e33a6bd0d71831e0c249816d01e6c1dd90a47/asm-util-5.1.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm-tree/5.1/87b38c12a0ea645791ead9d3e74ae5268d1d6c34/asm-tree-5.1.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm/5.1/5ef31c4fe953b1fd00b8a88fa1d6820e8785bb45/asm-5.1.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/org.jacoco/org.jacoco.report/0.7.4.201502262128/5c6bb5f95ae695dc4510b95f7d5ad0397e4881ad/org.jacoco.report-0.7.4.201502262128.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/org.jacoco/org.jacoco.core/0.7.4.201502262128/31482f50411a3a5769b6c78fa9b97ba731c205e7/org.jacoco.core-0.7.4.201502262128.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/net.sf.jopt-simple/jopt-simple/4.9/ee9e9eaa0a35360dcfeac129ff4923215fd65904/jopt-simple-4.9.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/net.sf.proguard/proguard-gradle/5.3.3/ad23a0505f58d0dfc95bb1472decc397460406c9/proguard-gradle-5.3.3.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/com.android.tools.analytics-library/tracker/26.0.1/15f0c0560c8a97700651d2dd5219937baa80c166/tracker-26.0.1.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/com.android.tools.analytics-library/shared/26.0.1/5cfc3811c2fd6cddfce2ec1bb5fbbec87e0fc462/shared-26.0.1.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/com.android.tools.analytics-library/protos/26.0.1/7719e7ed7498e25ec555bdfcb7a4de0e88a47ea/protos-26.0.1.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/com.google.protobuf/protobuf-java/3.0.0/6d325aa7c921661d84577c0a93d82da4df9fa4c8/protobuf-java-3.0.0.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-compiler-runner/1.2.41/c2bd43e2bf7d6f26e47fbdca79502b62fe130696/kotlin-compiler-runner-1.2.41.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/com.android.tools.build/builder-model/3.0.1/e9de7e34339a8eb90fda30ac6bf580d5f2c4f282/builder-model-3.0.1.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/com.android.tools.build/builder-test-api/3.0.1/5f084a2888a7f638c4c89c3278760345b1fb4c8/builder-test-api-3.0.1.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/com.android.tools.ddms/ddmlib/26.0.1/d4bcdb3a578812688ccc34f1359702601fea955d/ddmlib-26.0.1.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/com.android.tools.layoutlib/layoutlib-api/26.0.1/4eb1f46803873ff996f2457d1dd64c5c305818d8/layoutlib-api-26.0.1.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/com.android.tools/dvlib/26.0.1/46f3eeaf812811374b4ea2c49ad52687a7ff6a87/dvlib-26.0.1.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/com.android.tools/common/26.0.1/38e362a43a905b6745d609bea37faddb0c5bffab/common-26.0.1.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/com.android.tools.build/apksig/3.0.1/535b9323a1bd47e3a9c860d11f4e11a80db13f2b/apksig-3.0.1.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/com.squareup/javawriter/2.5.0/81241ff7078ef14f42ea2a8995fa09c096256e6b/javawriter-2.5.0.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcpkix-jdk15on/1.56/4648af70268b6fdb24674fb1fd7c1fcc73db1231/bcpkix-jdk15on-1.56.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcprov-jdk15on/1.56/a153c6f9744a3e9dd6feab5e210e1c9861362ec7/bcprov-jdk15on-1.56.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/it.unimi.dsi/fastutil/7.2.0/5ad3a2bb04143f70aa0765fc29fc29571a7d6b34/fastutil-7.2.0.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/com.googlecode.json-simple/json-simple/1.1/5e303a03d04e6788dddfa3655272580ae0fc13bb/json-simple-1.1.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/org.eclipse.jdt.core.compiler/ecj/4.6.1/5555607add54eb79c5a0729134e663fe2e6300c2/ecj-4.6.1.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/com.google.jimfs/jimfs/1.1/8fbd0579dc68aba6186935cc1bee21d2f3e7ec1c/jimfs-1.1.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/com.android.tools.external.lombok/lombok-ast/0.2.3/528b6f8bde3157f17530aa366631f2aad2a6cf9/lombok-ast-0.2.3.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/com.google.guava/guava/22.0/3564ef3803de51fb0530a8377ec6100b33b0d073/guava-22.0.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/com.android.databinding/baseLibrary/3.0.1/cc0483d84342e82c261aeb5fd0ef2f876b587489/baseLibrary-3.0.1.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/org.antlr/antlr4/4.5.3/f35db7e4b2446e4174ba6a73db7bd6b3e6bb5da1/antlr4-4.5.3.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/commons-io/commons-io/2.4/b1b6ea3b7e4aa4f492509a4952029cd8e48019ad/commons-io-2.4.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/com.googlecode.juniversalchardet/juniversalchardet/1.0.3/cd49678784c46aa8789c060538e0154013bb421b/juniversalchardet-1.0.3.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/com.android.tools/annotations/26.0.1/29012758503f56c7dc0714eda494f7f140fd3db8/annotations-26.0.1.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/org.jetbrains/annotations/13.0/919f0dfe192fb4e063e7dacadee7f8bb9a2672a9/annotations-13.0.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/net.sf.proguard/proguard-base/5.3.3/988b6b0636ce343d4962b3b37f6319dcc6e99a61/proguard-base-5.3.3.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-script-runtime/1.2.41/e291b12913910c260ce878f9a76c84203cf710a1/kotlin-script-runtime-1.2.41.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-build-common/1.2.41/3ca2f7f659163dfdb9f180b64e9964c7c176c171/kotlin-build-common-1.2.41.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-daemon-client/1.2.41/b9cb88843eeba0f43542daa00c7949e40e9e2852/kotlin-daemon-client-1.2.41.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/com.google.code.gson/gson/2.3/5fc52c41ef0239d1093a1eb7c3697036183677ce/gson-2.3.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/org.apache.commons/commons-compress/1.12/84caa68576e345eb5e7ae61a0e5a9229eb100d7b/commons-compress-1.12.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/org.apache.httpcomponents/httpclient/4.2.6/e4ca30a6a3a075053a61c6fc850d2432dc012ba7/httpclient-4.2.6.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/org.apache.httpcomponents/httpmime/4.1/9ba2dcdf94ce35c8a8e9bff242db0618ca932e92/httpmime-4.1.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/net.sf.kxml/kxml2/2.3.0/ccbc77a5fd907ef863c29f3596c6f54ffa4e9442/kxml2-2.3.0.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/com.google.code.findbugs/jsr305/1.3.9/40719ea6961c0cb6afaeb6a921eaa1f6afd4cfdf/jsr305-1.3.9.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/com.google.errorprone/error_prone_annotations/2.0.18/5f65affce1684999e2f4024983835efc3504012e/error_prone_annotations-2.0.18.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/com.google.j2objc/j2objc-annotations/1.1/976d8d30bebc251db406f2bdb3eb01962b5685b3/j2objc-annotations-1.1.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/org.codehaus.mojo/animal-sniffer-annotations/1.14/775b7e22fb10026eed3f86e8dc556dfafe35f2d5/animal-sniffer-annotations-1.14.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/com.intellij/annotations/12.0/bbcf6448f6d40abe506e2c83b70a3e8bfd2b4539/annotations-12.0.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/org.apache.httpcomponents/httpcore/4.2.5/472f0f5f8dba5d1962cb9d7739feed739a31c30d/httpcore-4.2.5.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/commons-logging/commons-logging/1.1.1/5043bfebc3db072ed80fbd362e7caf00e885d8ae/commons-logging-1.1.1.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/commons-codec/commons-codec/1.6/b7f0fc8f61ecadeb3695f0b9464755eee44374d4/commons-codec-1.6.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/com.android.tools.external.com-intellij/intellij-core/26.0.1/a373ed549821cb9a932b87c79792790f6d018727/intellij-core-26.0.1.jar, /Users/stefan/.gradle/caches/modules-2/files-2.1/org.jetbrains.trove4j/trove4j/20160824/33c3e174a9c8368d93761d3d12712db18e903959/trove4j-20160824.jar]

    availableSchema: ProjectSchema(extensions=[ProjectSchemaEntry(target=Accessible(type=org.gradle.api.Project), name=ext, type=Accessible(type=org.gradle.api.plugins.ExtraPropertiesExtension)), ProjectSchemaEntry(target=Accessible(type=org.gradle.api.Project), name=defaultArtifacts, type=Accessible(type=org.gradle.api.internal.plugins.DefaultArtifactPublicationSet)), ProjectSchemaEntry(target=Accessible(type=org.gradle.api.internal.plugins.DefaultArtifactPublicationSet), name=ext, type=Accessible(type=org.gradle.api.plugins.ExtraPropertiesExtension)), ProjectSchemaEntry(target=Accessible(type=org.gradle.api.Project), name=reporting, type=Accessible(type=org.gradle.api.reporting.ReportingExtension)), ProjectSchemaEntry(target=Accessible(type=org.gradle.api.reporting.ReportingExtension), name=ext, type=Accessible(type=org.gradle.api.plugins.ExtraPropertiesExtension)), ProjectSchemaEntry(target=Accessible(type=org.gradle.api.Project), name=buildOutputs, type=Accessible(type=org.gradle.api.NamedDomainObjectContainer<com.android.build.gradle.api.BaseVariantOutput>)), ProjectSchemaEntry(target=Accessible(type=org.gradle.api.NamedDomainObjectContainer<com.android.build.gradle.api.BaseVariantOutput>), name=ext, type=Accessible(type=org.gradle.api.plugins.ExtraPropertiesExtension)), ProjectSchemaEntry(target=Accessible(type=org.gradle.api.Project), name=android, type=Accessible(type=com.android.build.gradle.AppExtension)), ProjectSchemaEntry(target=Accessible(type=com.android.build.gradle.AppExtension), name=ext, type=Accessible(type=org.gradle.api.plugins.ExtraPropertiesExtension)), ProjectSchemaEntry(target=Accessible(type=com.android.build.gradle.AppExtension), name=kotlinOptions, type=Accessible(type=org.jetbrains.kotlin.gradle.dsl.KotlinJvmOptionsImpl)), ProjectSchemaEntry(target=Accessible(type=org.gradle.api.Project), name=kotlin, type=Accessible(type=org.jetbrains.kotlin.gradle.dsl.KotlinProjectExtension)), ProjectSchemaEntry(target=Accessible(type=org.jetbrains.kotlin.gradle.dsl.KotlinProjectExtension), name=ext, type=Accessible(type=org.gradle.api.plugins.ExtraPropertiesExtension)), ProjectSchemaEntry(target=Accessible(type=org.jetbrains.kotlin.gradle.dsl.KotlinProjectExtension), name=experimental, type=Accessible(type=org.jetbrains.kotlin.gradle.dsl.ExperimentalExtension)), ProjectSchemaEntry(target=Accessible(type=org.jetbrains.kotlin.gradle.dsl.ExperimentalExtension), name=ext, type=Accessible(type=org.gradle.api.plugins.ExtraPropertiesExtension)), ProjectSchemaEntry(target=Accessible(type=org.gradle.api.Project), name=kapt, type=Accessible(type=org.jetbrains.kotlin.gradle.plugin.KaptExtension)), ProjectSchemaEntry(target=Accessible(type=org.jetbrains.kotlin.gradle.plugin.KaptExtension), name=ext, type=Accessible(type=org.gradle.api.plugins.ExtraPropertiesExtension))], conventions=[ProjectSchemaEntry(target=Accessible(type=org.gradle.api.Project), name=base, type=Accessible(type=org.gradle.api.plugins.BasePluginConvention)), ProjectSchemaEntry(target=Accessible(type=org.gradle.api.Project), name=java, type=Accessible(type=org.gradle.api.plugins.JavaPluginConvention))], configurations=[androidJacocoAgent, androidJacocoAnt, androidTestAnnotationProcessor, androidTestApi, androidTestApk, androidTestCompile, androidTestCompileOnly, androidTestDebugAnnotationProcessor, androidTestDebugApi, androidTestDebugApk, androidTestDebugCompile, androidTestDebugCompileOnly, androidTestDebugImplementation, androidTestDebugProvided, androidTestDebugRuntimeOnly, androidTestDebugWearApp, androidTestImplementation, androidTestProvided, androidTestRuntimeOnly, androidTestUtil, androidTestWearApp, annotationProcessor, api, apk, archives, compile, compileOnly, debugAnnotationProcessor, debugApi, debugApk, debugCompile, debugCompileOnly, debugImplementation, debugProvided, debugRuntimeOnly, debugWearApp, default, implementation, kapt, kaptAndroidTest, kaptAndroidTestDebug, kaptDebug, kaptRelease, kaptTest, kaptTestDebug, kaptTestRelease, lintChecks, provided, releaseAnnotationProcessor, releaseApi, releaseApk, releaseCompile, releaseCompileOnly, releaseImplementation, releaseProvided, releaseRuntimeOnly, releaseWearApp, runtimeOnly, testAnnotationProcessor, testApi, testApk, testCompile, testCompileOnly, testDebugAnnotationProcessor, testDebugApi, testDebugApk, testDebugCompile, testDebugCompileOnly, testDebugImplementation, testDebugProvided, testDebugRuntimeOnly, testDebugWearApp, testImplementation, testProvided, testReleaseAnnotationProcessor, testReleaseApi, testReleaseApk, testReleaseCompile, testReleaseCompileOnly, testReleaseImplementation, testReleaseProvided, testReleaseRuntimeOnly, testReleaseWearApp, testRuntimeOnly, testWearApp, wearApp])
```

### Expected Behavior
The sample should work

### Current Behavior
The sample don't sync...

### Steps to Reproduce (for bugs)
Just checkout `this` repo, open the hello-android sample with android studio and try to sync the project.

### PR DESCRIPTION
**Pull request by bamboo**
By deserializing the Kotlin `ProtoBuf.Class` information stored in the `kotlin.Metadata` annotation. This is done only for public classes for performance reasons.

Fixes #856

### CODE REVIEW

File: provider/src/main/kotlin/org/gradle/kotlin/dsl/accessors/AccessorsClassPath.kt [hunk 1]
```diff
@@ -326,6 +352,64 @@ class HasTypeParameterClassVisitor : ClassVisitor(ASM6) {
...
+) : AnnotationVisitor(ASM6) {
+
+    /**
+     * @see kotlin.Metadata.d1
+     */
+    private
+    var d1 = mutableListOf<String>()
+
+    /**
+     * @see kotlin.Metadata.d1
```
Comment (eskatos) [inline provider/src/main/kotlin/org/gradle/kotlin/dsl/accessors/AccessorsClassPath.kt]: :x: should be `kotlin.Metadata.d2`
